#!/usr/bin/env bash

wrapper() {
  local ENVS="$(pipe-delim-vars 'RDS_*')"
  local USAGE="usage: rds-dbadmin [--skip-health-check] ${ENVS:-RDS_ENV} [login-only|create-user] [info|debug]"
  local INFO_FMT="INFO %-20s: %s\n"
  vecho "ENVS=$ENVS"
  vecho "USAGE=$USAGE"
  vecho "INFO_FMT=$INFO_FMT"
  vecho "\$1=$1"
  vecho "\$2=$2"

  local opt_login_only= opt_create_user= opt_skip_health_check=
  
  [[ "$1" =~ --skip-health-check|-s ]] && shift && opt_skip_health_check=1
  
  local opt_env="$1" && shift
  vecho "opt_env=$opt_env"
  [[ -z "$opt_env" ]] && eecho "$USAGE" && return 1
  
  local opt_action="$1"
  [[ -n "$opt_action" ]] && shift || opt_action='create-user'
  vecho "opt_action=$opt_action"
  if [[ "$opt_action" =~ ^l ]]; then
    opt_login_only=1
  elif [[ "$opt_action" =~ ^c ]]; then
    opt_create_user=1
  else
    eecho "$USAGE" && return 1
  fi
  local opt_log_level="${1:-info}" && shift

  export RDS_ENV="$(upper $opt_env)"
  pbcopy <<< "$RDS_ENV"
  printf "$INFO_FMT" "RDS_ENV" "$RDS_ENV"

  local db_host_v="RDS_${RDS_ENV}_HOST" && db_host="${!db_host_v}"
  [[ -z "$db_host" ]] && \
    eecho "rds-dbadmin: $opt_env: no host defined" && return 1
  export ${db_host_v}="$db_host"

  local db_cred_host_v="RDS_${RDS_ENV}_CRED_HOST" && db_cred_host="${!db_cred_host_v}" && \
    [[ -z "$db_cred_host" ]] && db_cred_host="$db_host"
  export ${db_cred_host_v}="$db_cred_host"
  
  pbcopy <<< "$db_host"
  printf "$INFO_FMT" "$db_host_v" "$db_host"
  printf "$INFO_FMT" "$db_cred_host_v" "$db_cred_host"
  printf "$INFO_FMT" "opt_action" "$opt_action"
  printf "$INFO_FMT" "opt_log_level" "$opt_log_level"


  if ((opt_skip_health_check)); then
    printf "INFO skipping dbadmin health check\n"
  else
    printf "INFO dbadmin health:\n"
    dbadmin --log-level $opt_log_level health || return 1
  fi


  printf "INFO dbadmin login:\n"
  dbadmin --log-level=$opt_log_level login || return 1


  local db_user db_user_v="RDS_${RDS_ENV}_USER"
  local db_cred db_cred_v="RDS_${RDS_ENV}_CRED"

  if ((opt_login_only)); then
    db_user="${!db_user_v}"
    db_cred="${!db_cred_v}"
    if [[ -z "$db_user" || -z "$db_cred" ]]; then
      eecho "rds-dbadmin: no username and/or credentials for $RDS_ENV; specify create-user"
      return 1
    fi
  fi

  if ((opt_create_user)); then
    local cmd="dbadmin --log-level=$opt_log_level --log-format=json create_user --endpoint "$db_cred_host""
    printf "\$ $cmd\n"

    local json="$HOME/tmp/rds-dbadmin.$$.json"
    if ! $cmd | tail -1 |tee "$json"; then
      eecho "rds-dbadmin: error: call to dbadmin create_user failed for $RDS_ENV"
      return 1
    elif [[ ! -s "$json" ]]; then
      eecho "rds-dbadmin: error: no response from create_user for $RDS_ENV" && return 1
    fi
    printf "$INFO_FMT" "json" "$(jq < "$json")"

    local db_user="$(jq -r '.username' < "$json")"
    local db_cred="$(jq -r '.password' < "$json")"
    if [[ -z "$db_user" || -z "$db_cred" ]]; then
      eecho "rds-dbadmin: error: bad response from create_user for $RDS_ENV"
      return 1
    fi
    
    printf "INFO Created user\n"
  fi

  export ${db_user_v}="$db_user"
  export ${db_cred_v}="$db_cred"

  echo -n "$db_user" | pbcopy  #<<<- "$db_user"
  sleep 0.25
  echo -n "$db_cred" | pbcopy  #<<< "$db_cred"

  printf "$INFO_FMT" "$db_user_v" "$db_user"
  printf "$INFO_FMT" "$db_cred_v" "$db_cred"

  if ((opt_create_user)); then
    printf '\n# ENV: %s (%s)\n' "$RDS_ENV" "$(date)" >> ~/.secrets.$USER
    printf '# HOST: %s\n' "$db_host" >> ~/.secrets.$USER
    printf '# CRED_HOST: %s\n' "$db_cred_host" >> ~/.secrets.$USER
    printf "export %s='%s'\n" "$db_user_v" "$db_user" >> ~/.secrets.$USER
    printf "export %s='%s'\n" "$db_cred_v" "$db_cred" >> ~/.secrets.$USER

    printf "\nSource ~/.secrets.$USER to load the $RDS_ENV environment's variables:\n"
    printf "$ tail ~/.secrets.$USER\n"
    tail -n 5 ~/.secrets.$USER
  fi
}

eecho() { >&2 echo "$*"; return 0; }

pipe-delim-vars() {
  local patt="$1" && shift
  for v in $(eval "echo $(printf "\${!%s}\n" "$patt")"); do 
    [[ $v =~ _HOST$ ]] && cut -d'_' -f 2 <<< $v
  done |\
  join-lines '|'
}

wrapper "$@"
unset -f wrappeer