#!/usr/bin/env bash

rds-pgcli() {
  local db_env="${1:-$RDS_ENV}" && shift
  [[ -z "$db_env" ]] && >&2 echo "usage: rds-pgcli db_env [db_name]" && return 1
  export RDS_ENV="$(upper "$db_env")"
  pbcopy <<< "$RD_ENV"
  
  local db_name="$1" && shift

  local db_host="RDS_${RDS_ENV}_HOST"
  db_host="${!db_host}"
  [[ -z "$db_host" ]] && >&2 echo "rds-pgcli: $db_env: no environment defined" && return 1
  pbcopy <<< "$db_host"
  echo "RDS_ENV: [$RDS_ENV]"

  local db_user="RDS_${RDS_ENV}_USER"
  db_user="${!db_user}"
  [[ -z "$db_user" ]] && >&2 echo "rds-pgcli: $db_env: no user defined" && return 1
  pbcopy <<< "$db_user"
  echo "db_user: [$db_user]"

  local db_cred="RDS_${RDS_ENV}_CRED"
  db_cred="${!db_cred}"
  if [[ -z "$db_cred" ]]; then
    >&2 echo "rds-pgcli: warning: no password defined"
  else
    pbcopy <<< "$db_cred"
    echo "db_cred: [${db_cred:0:2}***${db_cred:$((${#db_cred}-2))}]"
  fi

  local opt_db="--list" && [[ -n "$db_name" ]] && opt_db="-d $db_name"

  echo "pgcli -h "$db_host" -u "$db_user" $opt_db"
  pgcli -h "$db_host" -u "$db_user" $opt_db

}
rds-pgcli "$@"
