#!/usr/bin/env bash

wrapper() {
  local SH_VERBOSE=$SH_VERBOSE SH_QUIET=$SH_QUIET
  local opt_log_level=info opt_skip_health_check=
  while [[ "$1" =~ ^(-[[:alpha:]]|--[[:alpha:]]+)$ ]]; do
    [[ "$1" =~ -v|--verbose ]] && SH_VERBOSE=1 && opt_log_level=debug && shift && continue
    [[ "$1" =~ -q|--quiet ]] && SH_QUIET=1 && opt_log_level=warn && shift && continue
    [[ "$1" =~ -s|--skip-health-check ]] && opt_skip_health_check=1 && shift && continue
  done

  local ENVS="$(pipe-delim-vars 'RDS_*')"
  local USAGE="usage: rds-dbadmin [-v|-q] [--skip-health-check] ${ENVS:-RDS_ENV}"
  local INFO_FMT="INFO %-20s: %s\n"
  vprintf "$INFO_FMT" 'ENVS' "$ENVS"
  vprintf "$INFO_FMT" 'opt_log_level' "$opt_log_level"
  vprintf "$INFO_FMT" 'opt_skip_health_check' "$opt_skip_health_check"
  vprintf "$INFO_FMT" '$1' "$1"

  export RDS_ENV="$(upper "$1")" && shift
  [[ -z "$RDS_ENV" ]] && eecho "$USAGE" && return 1
  pbcopy <<< "$RDS_ENV" && sleep 0.1
  qprintf "$INFO_FMT" "RDS_ENV" "$RDS_ENV"

  local db_host_v=RDS_${RDS_ENV}_HOST
  export RDS_HOST="${!db_host_v}"
  [[ -z "$RDS_HOST" ]] && eecho "rds-dbadmin: $opt_env: no host defined" && return 1
  qprintf "$INFO_FMT" $db_host_v "$RDS_HOST"
  export ${db_host_v}="$RDS_HOST"
  echo -n "$RDS_HOST" | pbcopy && sleep 0.1

  local db_cred_host_v=RDS_${RDS_ENV}_CRED_HOST && local db_cred_host="${!db_cred_host_v}"
  [[ -z "$db_cred_host" ]] && db_cred_host="$RDS_HOST"
  export ${db_cred_host_v}="$db_cred_host"
  qprintf "$INFO_FMT" $db_cred_host_v "$db_cred_host"


  if ((opt_skip_health_check)); then
    qecho "INFO skipping dbadmin health check"
  else
    qecho "INFO dbadmin health:"
    dbadmin --log-level $opt_log_level health || return 1
  fi


  qecho "INFO dbadmin login:"
  dbadmin --log-level=$opt_log_level login || return 1


  local cmd="dbadmin --log-level=$opt_log_level --log-format=json create_user --endpoint "$db_cred_host""
  qecho ">\$ $cmd"

  local json="$HOME/tmp/rds-dbadmin.$$.json"
  if ! $cmd | tail -1 |tee "$json"; then
    eecho "rds-dbadmin: error: call to dbadmin create_user failed for $RDS_ENV"
    return 1
  elif [[ ! -s "$json" ]]; then
    eecho "rds-dbadmin: error: no response from create_user for $RDS_ENV" && return 1
  fi
  vprintf "$INFO_FMT" "json" "$(jq < "$json")"

  local db_user_v=RDS_${RDS_ENV}_USER
  local db_cred_v=RDS_${RDS_ENV}_CRED

  export RDS_USER="$(jq -r '.username' < "$json")"
  export RDS_CRED="$(jq -r '.password' < "$json")"
  if [[ -z "$RDS_USER" || -z "$RDS_CRED" ]]; then
    eecho "rds-dbadmin: error: bad response from create_user for $RDS_ENV"
    return 1
  fi
  
  qecho "INFO Created user"


  export ${db_user_v}="$RDS_USER"
  export ${db_cred_v}="$RDS_CRED"

  echo -n "$RDS_USER" | pbcopy && sleep 0.1 #<<<- "$RDS_USER"
  echo -n "$RDS_CRED" | pbcopy && sleep 0.1 #<<< "$RDS_CRED"

  qprintf "$INFO_FMT" "$db_user_v" "$RDS_USER"
  qprintf "$INFO_FMT" "$db_cred_v" "$RDS_CRED"

  if ((opt_create_user)); then
    printf '\n# ENV: %s (%s)\n' "$RDS_ENV" "$(date)" >> ~/.secrets.$USER
    printf '# HOST: %s\n' "$db_host" >> ~/.secrets.$USER
    printf '# CRED_HOST: %s\n' "$db_cred_host" >> ~/.secrets.$USER
    printf "export %s='%s'\n" "$db_user_v" "$RDS_USER" >> ~/.secrets.$USER
    printf "export %s='%s'\n" "$db_cred_v" "$RDS_CRED" >> ~/.secrets.$USER

    printf "\nSource ~/.secrets.$USER to load the $RDS_ENV environment's variables:\n"
    printf "$ tail ~/.secrets.$USER\n"
    tail -n 5 ~/.secrets.$USER
  fi
}

pipe-delim-vars() {
  local patt="$1" && shift
  for v in $(eval "echo $(printf "\${!%s}\n" "$patt")"); do 
    [[ $v =~ _HOST$ ]] && cut -d'_' -f 2 <<< $v
  done |\
  join-lines '|'
}

wrapper "$@"
unset -f wrapper