#!/usr/bin/env bash

# Note that `pbcopy <<< "string"` adds an implicit linefeed.

wrapper() {

  local SH_VERBOSE=$SH_VERBOSE SH_QUIET=$SH_QUIET
  local info_fmt="INFO %-20s: %s\n"
  local envs="$(pipe-delim-vars 'RDS_*' '_HOST$' '_CRED_HOST$')"
  local usage="usage: rds-pgcli [-v|-q] [--tunnel] ${envs:-ENV} [db_name]"

  while [[ "$1" =~ ^(-[[:alpha:]]|--[[:alpha:]]+)$ ]]; do
    case "$1" in
      -v|--verbose) SH_VERBOSE=1 SH_QUIET=;;
      -q|--quiet) SH_QUIET=1 SH_VERBOSE=;;
      -t|--tunnel) opt_tunnel=1;;
      *) break;;
    esac
    shift
  done

  vprintf "$info_fmt" opt_tunnel "$opt_tunnel"

  [[ -z "$1" ]] && eecho "$usage" && return 1
  export RDS_ENV="$(upper "$1")" && shift
  pbcopy <<< "$RDS_ENV" && sleep 0.1
  qprintf "$info_fmt" RDS_ENV "$RDS_ENV"
  
  if [[ -n "$1" ]]; then
    export PGDATABASE="$1" && shift
    pbcopy <<< "$PGDATABASE" && sleep 0.1
  fi
  qprintf "$info_fmt" PGDATABASE "$PGDATABASE"
    # local opt_db="--list" && [[ -n "$PGDATABASE" ]] && opt_db="-d $PGDATABASE"
    # vprintf "$info_fmt" opt_db "$opt_db"


  export PGHOST="$(eval echo \$RDS_${RDS_ENV}_HOST)"
  [[ -z "$PGHOST" ]] && eecho "rds-pgcli: $RDS_ENV: no host defined" && return 1
  echo -n "$PGHOST" | pbcopy && sleep 0.1
  qprintf "$info_fmt" PGHOST "$PGHOST"

  export PGUSER="$(eval echo \$RDS_${RDS_ENV}_USER)"
  [[ -z "$PGUSER" ]] && eecho "rds-pgcli: $RDS_ENV: no user defined" && return 1
  echo -n "$PGUSER" | pbcopy && sleep 0.1
  qprintf "$info_fmt" PGUSER "$PGUSER"

  export PGPASSWORD="$(eval echo \$RDS_${RDS_ENV}_CRED)"
  [[ -z "$PGPASSWORD" ]] && eecho "rds-pgcli: $RDS_ENV: no password defined" && return 1
  echo -n "$PGPASSWORD" | pbcopy && sleep 0.1
  qprintf "$info_fmt" PGPASSWORD "$PGPASSWORD"


  local opt_local_port=5432
  if ((opt_tunnel)); then
    opt_local_port=5433
    if nc -z localhost $opt_local_port; then
      qecho "Tunnelling to already-open port $opt_local_port"
    else
      qecho "Creating tunnel on local port $opt_local_port"
      qeval ssh -f -p 22 -L localhost:$opt_local_port:$PGHOST:5432 -N toddpierzina@bastion.aws.uswest2.cchh.io
    fi
    PGHOST=localhost
  fi
  
  qeval pgcli -p $opt_local_port $( [[ -n "$PGDATABASE" ]] && echo "-d $PGDATABASE" || echo '--list' )
}

pipe-delim-vars() {
  local glob_pattern="$1"; shift
  local regex_accept_pattern="$1"; shift
  local regex_reject_pattern="$1"; shift
  for v in $(eval "echo $(printf "\${!%s}\n" "$glob_pattern")"); do
    [[ ! "$v" =~ ${regex_accept_pattern:-.} ]] && continue
    [[ -n "$regex_reject_pattern" && "$v" =~ $regex_reject_pattern ]] && continue
    cut -d'_' -f 2 <<< $v
  done |\
  join-lines '|'

}

wrapper "$@"
unset -f wrappeer

